### ISSUE TITLE
Building Instructions

### ISSUE THREAD

**Issue by chaitanyaphalak** [cloudfoundry/loggregator#294] opened 2017-07-27 21:15 UTC
I want to get up and running with this project. I am new to GO and couldn't build this. Would appreciate it if there are instructions to get it up and running.

**Comment by ahevenor** [comment] 2017-07-27 21:39
Hi Chaitanya - 

Thanks for the feedback. Loggregator is a [bosh](http://bosh.io/) release generally run as a component of [cf-release](https://github.com/cloudfoundry/cf-release) or [cf-deployment](https://github.com/cloudfoundry/cf-deployment/) - two ways of packaging and deploying Cloud Foundry as a whole. In practice this means that our repo is actually made up of several sub components that you build individually. In general this makes Loggregator a tough projects to try and learn golang on. You could try building our logspinner application in /src/tools/logspinner. You would find this to be an easier starting point.

I am going to close this item for tracking purposes. 

Thanks
Adam

**Closed by ahevenor** 2017-07-27 21:39 UTC
Labels: unscheduled

**Comment by chenziliang** [comment] 2017-07-27 22:12
@ahevenor May i ask is it possible to build logaggrator only and get it up and running in standablone ?

**Comment by ahevenor** [comment] 2017-07-27 22:15
@chenziliang you could build /src/metron standalone. Also worth noting two of the Loggregator team members have produced the [go build it video series](https://gobuildit.github.io/). Great resource for learning golang.

**Comment by chenziliang** [comment] 2017-07-27 22:28
The purpose of building the logaggrator alone is i would like to run logaggrator as a standalone system. the i can update golang source code of logaggrator for testing purpose.

**Comment by ahevenor** [comment] 2017-07-28 19:51
@chenziliang you can use [/scripts/build](https://github.com/cloudfoundry/loggregator/blob/develop/scripts/build) to build locally.

**Comment by enocom** [comment] 2017-07-29 15:09
@chenziliang As Adam mentioned, we treat Bosh as the first class means for deploying Loggregator. In fact, you can easily build Loggregator and run it standalone, but it will require a lot of configuration tweaking that currently we do not provide. Take a look inside `src/code.cloudfoundry.org/loggregator`. All the loggregator components live in there and can be built with a simple `go build` within each component's directory.

**Comment by chenziliang** [comment] 2017-07-29 15:20
@enocom @ahevenor  Appreciate for your responses. I believe i figured that out by setting up the GOPATH correctly and then run scripts/build to build everything. 

BTW, since you guys are experts of logaggrator, did you happen to know what is the cause of this issue ? https://github.com/cloudfoundry/loggregator/issues/295

Thanks again !
