### ISSUE TITLE
Reconfigure loggregator buffer to avoid "log message output too high. we've dropped 100 messages"

### ISSUE THREAD

**Issue by svennela** [cloudfoundry/loggregator#64] opened 2015-07-20 17:11 UTC
Customer comments..

Hello, 
Can we reconfigure loggregator buffer from 100 to a higher number to avoid seeing frequent "log message output too high. we've dropped 100 messages". We have gone through the explaination on http://support.run.pivotal.io/entries/79609435-Troubleshooting-dropped-or-missing-log-messages but believe we may have some benefits for java heap dumps too occassionally with higher value especially for Development spaces.

**Comment by EngineerBetter** [comment] 2015-07-21 08:43
I've raised two other [related](https://github.com/cloudfoundry/loggregator/issues/67) [issues](https://github.com/cloudfoundry/loggregator/issues/66) that contribute to problems of the buffer size being too small.

This was discussed on the mailing list some time ago, but 100 messages really is too small for Java applications. Logged exceptions can easily run to hundreds of lines long, per instance of the exception thrown and then logged. In any system with a reasonable amount of load, one could expect such an exception to occur rather frequently.

Whilst more Doppler instances can be added, do we really need a whole VM to be provisioned so we can get another 100-message buffer?

**Comment by EngineerBetter** [comment] 2015-07-21 09:11
Another thing in case it gets lost in the support issue: could the Loggregator team be able to propose a test that they would accept as evidence that the problem is not with the speed of the downstream Syslog client?

**Comment by ajackson** [comment] 2015-07-21 13:28
A great test to prove if the downstream client is too slow or if we have bugs in the server is the following.

Startup nc on a machine local to the server (ie not on a WAN).   Make sure the server is running on a multicore machine.   Point the syslog drain at the nc ip:port and flow logs into loggregator from a single application.  

We do want to change the code to allow the buffer size to be configurable.   This will allow folks to tune their memory usage vs log size.

**Comment by YannRobert** [comment] 2015-07-21 14:50
In case of a Java application, where a single log event can print on more than 100 lines (like the one @EngineerBetter shared on screenshot), the buffer will fill up instantly.

Cloud Foundry promotes scalability, meaning you could, if you wanted or needed, run (as) many instances (as you need) of an application. But you can never use that in practice, because however reasonable the workload is on each instance, logs are merged on loggregator and the buffer will endup being full at some point if not always.

Cloud Foundry promotes to work for many environments, including Java. But in the case of Java, applications are just chatty. And I'm sure there are other applications not even in Java where logs are important.

Because logs are important, because you just cannot say your stockholder "we have truncated logs, we have not clue of what happened", Cloud Foundry must provide a way to ensure, to the extends of the possible, that logs are not truncated. Otherwise, it will be a no go for Cloud Foundry.

I ended up using a syslog appender to directly send the log from Java applications to the syslog endpoint. [1] This never failed since I introduced this. Also, I never found that the endpoint could not keep up with the flow, be it 100 messages at once, or much much more.

I found the hosted SaaS syslog endpoint is always more available and capable to keep up, than the loggregator of the Cloud Foundry hosting the applications.

So this have to be possible with Cloud Foundry.

@ajackson some time ago you were mentioned [2]
```
Alex also mentioned a "crazy idea" of potentially getting rid of the Doppler servers and have every node, where the Metron currently resides, buffer the log lines locally and provide a more distributed architecture
```
That would provide scalability to Cloud Foundry application logging, as long a the endpoint is available.
Is there any chance to see that coming soon?

Cheers \( ﾟ◡ﾟ)/

[1] https://groups.google.com/a/cloudfoundry.org/d/msg/vcap-dev/xRi_TNo58aE/a67LzxYWg2wJ
[2] https://www.activestate.com/blog/2015/03/loggregator-voice-cloud-foundry

**Comment by EngineerBetter** [comment] 2015-07-21 15:43
@YannRobert said "In case of a Java application, where a single log event can print on more than 100 lines (like the one @EngineerBetter shared on screenshot), the buffer will fill up instantly."

I'm not certain that it would fill up instantly. Messages will arrive one at a time, and they _should_ be being removed one at a time too. If they are leaving the buffer (which let's face it, is really a queue) more slowly than they're going in, _then_ the buffer will fill up.

I've created [this issue](https://github.com/cloudfoundry/loggregator/issues/66) because via static analysis (with my eyes, which isn't terribly reliable) it looks like the outgoing messages are inadvertantly being throttled to one per millisecond. In the inbound channel is consumed from without this throttling, then that would explain why Doppler is the slow point compared to using a Syslog Appender going to the syslog endpoint directly.

**Comment by roxtar** [comment] 2015-09-22 03:08
It is now possible to configure the doppler message drain buffer size. See https://github.com/cloudfoundry/loggregator/blob/develop/bosh/jobs/doppler/spec#L60-L62 Closing.

**Closed by roxtar** 2015-09-22 03:08 UTC

**Comment by gcoon151** [comment] 2017-06-27 19:51
I know this is a dated issue but it's exactly the conversation I'm looking for and @roxtar link is dead now FYI.
