### ISSUE TITLE
enable message filtering of firehose data to stream specific type of events

### ISSUE THREAD

**Issue by boyang9527** [cloudfoundry/loggregator#155] opened 2016-09-29 22:58 UTC
Firehose today streams all types of events. If only specific type of events is needed, the user still has to get all from firehose and do filtering by him/herself.   For large scale deployment, this will cause huge network traffic along the path doppler->trafficcontroller->firehose nozzle. 

Propose to have an API  to stream only specific type of events, something like following

/events/EVENT_TYPE/SUBSCRIPTION_ID : Opens a websocket connection that streams the given type of events. Connections with the same subscription id will get an equal portion of the data.

**Comment by rboykin** [comment] 2016-10-11 10:34
+1

I could also use this for the Administration UI.  Though in that case, it would desirable to be able to retrieve both ContainerMetrics and ValueMetrics with one websocket connection.

**Comment by ahevenor** [comment] 2016-11-30 17:09
@boyang9527 and @rboykin - this is a great feature suggestion and validates some assumptions we have about the usefulness of the firehouse.

**Comment by jasonkeene** [comment] 2017-01-24 16:02
@ahevenor I did not see a story in our icebox to track this so I created one: https://www.pivotaltracker.com/story/show/138250011

I think it would be valuable to reduce network traffic between D -> TC and from TC -> client.

**Comment by ahevenor** [comment] 2017-03-20 21:46
This functionality is planed for the v2 loggregator API. We'll keep this issue open until this available for general use.

**Comment by boyang9527** [comment] 2017-03-21 22:36
@ahevenor, any ideas on when v2 API will be available?

**Comment by jasonkeene** [comment] 2017-03-23 15:31
This functionality has started to be added to the [v2 gRPC API](https://github.com/cloudfoundry/loggregator-api/blob/91f7b8287c6744901bc1af8a27cdccc454305059/v2/egress.proto#L16-L25). Not only will this work need to be completed but we will need to have the gorouter support http2.

**Comment by ahevenor** [comment] 2017-04-03 21:07
We now have a story to enable this capability in the websocket (v1) API: https://www.pivotaltracker.com/story/show/142851601

**Comment by ahevenor** [comment] 2017-05-17 22:05
@boyang9527 @rboykin - we have added some basic filtering to be released in the next Loggregator version. It currently only supports two filter types logs or metrics.

See the documentation [here](https://github.com/cloudfoundry/loggregator/blob/7ef17f3632a19df1fda5a53f29b3d9e7e4dc3f47/docs/firehose.md)

**Comment by rboykin** [comment] 2017-05-18 10:42
@ahevenor Thank you.  In which cf-release do you expect this function to appear?

**Comment by ahevenor** [comment] 2017-05-18 15:16
@boyang9527 - httpstarstop is included in the metrics version. It's grouped as logs, not logs.

@rboykin I would guess cf262. I'll drop a note in here when it is confirmed included.

**Comment by ahevenor** [comment] 2017-06-20 18:17
This is now available in the latest cf-release. Marking this item as delivered.

**Comment by apoydence** [comment] 2017-07-10 13:06
It looks like all the expected functionality has been delivered. I'm going to close this issue.

**Closed by apoydence** 2017-07-10 13:06 UTC
Labels: delivered
