### ISSUE TITLE
Applications exiting within 10-20ms of startup lose logs

### ISSUE THREAD

**Issue by Jonty** [cloudfoundry/loggregator#86] opened 2015-10-02 16:22 UTC
If an application starts and immediately crashes/quits, anything outputted to stdout/err is not logged which makes debugging quite hard. On our deployments it seems to affect anything that dies within 10-20ms.

The workaround for this is to change the Procfile to have a sleep statement in it, e.g. ````web: sleep 1 && command````.

I'm not sure if this is the correct place to file this issue, but I figured it was a good start.

This can be replicated by uploading a simple application that outputs something to stdout and immediately quits, such as ````example.go````:

````
func main() {
    println("This will not appear in the application logs")
}
````

**Comment by Jim-Campbell** [comment] 2015-10-02 17:25
Thanks, @Jonty, for reporting this.

This is indeed an unfortunate issue that we have experienced ourselves. Its root cause is hidden in the logic of the DEA Logging Agent for discovering and connecting to stdout/stderr on app containers when they are started on the DEA.

This issue is not present in Diego and so this will not be an issue when you switch from DEAs to Diego when you push your app. Note that DEA is being deprecated in favor of Diego. If you have a CF deployment that has Diego available, then just try to enable diego for your app and you should be fine. See [here](https://github.com/cloudfoundry-incubator/diego-cli-plugin) for instructions on how to enable diego for your app.

Given that this is only an issue with the DEA, which are being deprecated, and you do have a workaround, I am going to close this issue. If you feel that this has to be addressed despite the workarounds, please let us know and reopen the issue.

**Closed** 2015-10-02 21:27 UTC
