### ISSUE TITLE
Loggregator dropping logs

### ISSUE THREAD

**Issue by saliceti** [cloudfoundry/loggregator#247] opened 2017-04-03 17:08 UTC
We run [acceptance tests in our CI](https://github.com/alphagov/paas-cf/blob/e53123a3550e80f21cdcb7e6ae49ad5de11e81bb/concourse/pipelines/create-cloudfoundry.yml#L2043) for any change to our [Cloudfoundry setup](https://github.com/alphagov/paas-cf/tree/e53123a3550e80f21cdcb7e6ae49ad5de11e81bb/manifests/cf-manifest/manifest). We are currently using CF v253 which includes loggregator v79. This runs in AWS eu-west-1.

Recently they have started failing randomly and this has seriously decreased our productivity since almost none of our changes were going through the pipeline.

The failing tests are always related to logs. Many tests connect via `cf logs` and expect a specific message. And this message never arrives.

We have run the [loggregator smoke tests](https://github.com/cloudfoundry/loggregator/tree/develop/src/tools/smokes) to isolate the problem and we indeed loose a significant number of messages.
We send 10000 messages with a delay between 5us and 1ms. We sometimes get the 10000 messages back, but often we receive much less (down to 3000).

It is not obvious that it is related to the load as it is very irregular: sometimes it fails for 1ms and succeeds with 5us.

We have obeserved the metron agent on the cells drops UDP packets most when messages are lost.

We can force the error by:

* [Stressing the CPU](https://people.seas.harvard.edu/~apw/stress/) on the cells up to 0% idle
* [Saturating the network](https://iperf.fr/) between the cells and dopplers

However, this creates an unrealistic load, much higher than the acceptance tests create.

What we have tried so far:

* Increase the number of cells from 2 to 6 (Recommended by the loggregator team)
* Increase the number of dopplers from 2 to 6
* Increase the doppler drain buffer size to 100000
* Recompiled metron to stop recycling connections (looked better for some time but maybe redherring)
* Reduced the [acceptance test nodes](https://github.com/alphagov/paas-cf/blob/e53123a3550e80f21cdcb7e6ae49ad5de11e81bb/manifests/cf-manifest/manifest/900-cf-tests.yml#L3-L26) from 10 to 5. The tests take longer but this is the only thing working right now.
* Revert CF to v250. The behaviour looks slightly different. We still loose messages, but in a more consistent way. For example for 50-100us delay we always loose about 1000 messages. For 5 us, we always loose about 3000.

**Comment by ahevenor** [comment] 2017-04-03 17:38
@saliceti thanks for this issue. It's a helpful piece of feedback for us. A few thoughts. 

1. The predictability seems logical given the changes introduced in Loggregator 72. Essentially all loss is moving to UDP which is consistent with your results. 
1. The controlled experiments results are worth focusing on further. A few more things to consider. 
 * Do you have firehose nozzles? Are they appropriately scaled? 
 * Are you using syslog drains? How many are they fast enough to keep up? 
1. We recommend running the loggregator smoke tests regularly to determine ongoing message reliability and look for any potential patterns to message reliability fluctuations. 
1. There are other reasons we see `cf logs` fail at times for tests. The websocket connection can be slow to connect and timeout. it is worth ensuring you have appropriate timeouts on tests that rely on `cf logs`. 

Also, are you using any tools for monitoring metrics? There are several metrics to look at while these tests run as well that can help us further isolate loss and help with scaling.

**Comment by saliceti** [comment] 2017-04-04 14:10
Hi @ahevenor, thanks for your help.

* We use [graphite nozzle](https://github.com/alphagov/paas-graphite-nozzle) and [datadog nozzle](https://github.com/cloudfoundry-incubator/datadog-firehose-nozzle-release). I've stopped both and logs are still dropped
* We don't use any syslog drains, except the ones the acceptance tests may configure. We have syslog configured on the VMs to ship logs to [logsearch](https://github.com/logsearch/logsearch-boshrelease) but I believe this is different.
* I have added a job to [run the smoke tests continuously](https://github.com/alphagov/paas-cf/blob/142302879_loggregator_smoke_test/concourse/pipelines/create-cloudfoundry.yml#L2567-L2608). Let's see if we can find a pattern.
* Regarding the `cf logs` timeouts, we only use the [acceptance tests](https://github.com/cloudfoundry/cf-acceptance-tests) defaults.
* We use datadog for monitoring. Which metrics would you recommend we should monitor?

**Comment by ahevenor** [comment] 2017-04-05 16:42
@saliceti here some charts I setup in datadog for monitoring - and they do show increased loss starting when we deployed CF 253. The increase in `doppler.loggregator.dropped` is not so surprising but the `doppler.shedEnvelopes` increase is unexpected.  I'd be curious to know if you are seeing the same.

```
{
	"viz": "timeseries",
	"requests": [{
		"q": "ewma_20(per_second(avg:datadog.nozzle.doppler.loggregator.dropped{*}))",
		"aggregator": "avg",
		"style": {
			"palette": "cool"
		},
		"type": "line",
		"conditional_formats": []
	}, {
		"q": "ewma_20(per_second(avg:datadog.nozzle.DopplerServer.doppler.shedEnvelopes{*}))",
		"style": {
			"palette": "cool"
		},
		"type": "line"
	}],
	"autoscale": true
}
```

We also post our smoke tests results into datadog. They show more volatility but the ramp is not as as obvious as it is with the above chart. We happen to have a separate bug already created on this [here](https://www.pivotaltracker.com/story/show/142336227) which is currently at the top of our backlog. I'll keep you posted on what we have found out.

**Comment by saliceti** [comment] 2017-04-05 17:31
I can't see the metrics `*.doppler.loggregator.dropped` and `*.DopplerServer.doppler.shedEnvelopes` in our datadog.
They don't even appear in `cf nozzle -no-filter` either.
Any idea?

**Comment by ahevenor** [comment] 2017-04-05 20:29
@saliceti that implies you are not dropping anything out of these particular buffers (it requires a bit of effort to force). To confirm that you are configured correctly can you also look at `doppler.loggregator.ingress` and ensure it is coming through the firehose.

**Comment by saliceti** [comment] 2017-04-05 22:40
Is it that one?

```
origin:"doppler" eventType:CounterEvent timestamp:1491431932910955545 deployment:"" job:"" index:"" ip:"" tags:<key:"metric_version" value:"2.0" > tags:<key:"prefix" value:"loggregator" > counterEvent:<name:"loggregator.ingress" delta:0 total:894620 >  
origin:"metron" eventType:CounterEvent timestamp:1491431933978336986 deployment:"colin2017" job:"uaa" index:"80b2258e-af01-4dfe-a032-8b51c1831579" ip:"" tags:<key:"metric_version" value:"2.0" > tags:<key:"prefix" value:"loggregator" > counterEvent:<name:"loggregator.ingress" delta:0 total:238324 >  
```

**Comment by ahevenor** [comment] 2017-04-06 15:22
Those are correct. 

Are you able to monitor network io on dopplers? One thing we are investigating is an increase in network io there. 

Also, how have the smoke tests looked the last ~24 hours?

**Comment by saliceti** [comment] 2017-04-06 15:59
I'm seeing significant network usage on our 2 doppler VMs when the smoke test runs, up to 8-9 Mb/s. But the doppler VMs are `m3.medium` and should handle that easily?

The smoke tests are failing at random and I couldn't find any pattern. However, I tried a few things:

* Stopped the graphite nozzle
* Stopped a test app with 180 instances
* Stopped our CF smoke tests that run continuously
* Stopped the datadog nozzle (2 instances)

Finally there was no message dropped.
I started 1 instance of the datadog nozzle and I started to see dropped messages, like 2000-4000. So it definitely looks suspicious.
Following the [scaling nozzle doc](https://docs.cloudfoundry.org/loggregator/log-ops-guide.html#scaling-nozzles), I added the other instance. It looked a bit better, I could see more tests passing, and when it was failing there was about 2500 dropped messages.
I then added 2 more nozzles but the performance degraded and tests didn't pass.

I'm going to update the datadog nozzle now as we're not using the latest version.

**Comment by saliceti** [comment] 2017-04-06 16:56
The latest datadog nozzle hasn't improved things

This is how the smoke tests looked today:

![screen shot 2017-04-06 at 17 52 35](https://cloud.githubusercontent.com/assets/8416694/24766109/03ed2a44-1af2-11e7-9f17-9e78a1f94f56.png)

The drain (via POST) is really bad but I'd rather focus on fixing the `cf logs` first.

**Comment by ahevenor** [comment] 2017-04-06 17:32
We are also seeing corresponding network usage increase.  It seems within healthy bounds but we noticed at the upgrade path point from CF252 -> CF253. It's not conclusively linked to anything but is something we are noting with our test environments.

**Comment by ahevenor** [comment] 2017-04-06 17:37
Agreed. Let's focus on `cf logs`. There are some known deficiencies with drain we are working on a new architecture for and it should be completed soon. 

What is the above delay set in the smoke test for the charts above?

**Comment by saliceti** [comment] 2017-04-06 18:16
The delay is set to 5us. But I was seeing dropped messages for 100us as well.

**Comment by ahevenor** [comment] 2017-04-10 17:33
Thanks for sharing your results. 

We have been running smokes against several versions of loggregator over the weekend with a consistent delay (we're running 2us but the specific delay is less important than the historical comparison). 

Our results are showing that there is a 4-5% degradation in message reliability between Loggregator 76 vs later versions. We are testing starting some additional tests now to test some theories on root cause.

**Comment by ahevenor** [comment] 2017-04-13 16:17
@saliceti we have identified a fix for this and brought our smokes back to equivalent performance of Loggregator 76. This is currently on our develop branch and we'll be cutting a new release soon. 

![](https://www.pivotaltracker.com/story/show/143534419/comments/168673667)

**Comment by ahevenor** [comment] 2017-04-14 20:40
The fix for this now available in [Loggregator 84](https://github.com/cloudfoundry/loggregator/releases/tag/v84). I'll plan to close this issue when this is packaged in cf-release. 

cc @dsabeti

**Comment by saliceti** [comment] 2017-04-18 11:10
Thanks @ahevenor . We'll test with the new cf release when it's included.

**Comment by ahevenor** [comment] 2017-04-19 15:41
@saliceti this is now included in [CF-257](https://github.com/cloudfoundry/cf-release/releases/tag/v257)

**Comment by dcarley** [comment] 2017-04-20 15:09
@ahevenor Thanks. Would you be able to link us to the commits that fixed the problem so that we can understand it better?

**Comment by ahevenor** [comment] 2017-04-20 15:48
@dcarley there is a list available in this [story](https://www.pivotaltracker.com/story/show/143887961)

**Comment by dcarley** [comment] 2017-04-20 15:52
Excellent, thank you.

**Comment by ahevenor** [comment] 2017-04-24 20:15
@saliceti I am going to close this based on our results of running CF-257 vs CF-253. Please let us know if you don't see an improvement in message reliability in your deploy.

**Closed by ahevenor** 2017-04-24 20:15 UTC
Labels: delivered

**Comment by saliceti** [comment] 2017-04-25 08:25
Thanks, I'll test with CF 257 soonish.
